### PR TITLE
v1.9.1 recenter_tc - VERSION RELEASE main - remove GEOIPS_BASEDIR

### PR DESCRIPTION
**Pull request by mindyls**
# Related Issues
required to close NRLMMD-GEOIPS/geoips#127

# Reviewer Instructions
* Please confirm most recent completed pull request is labeled "DEVELOPMENTAL UPDATE" or "VERSION RELEASE":
    * https://github.com/NRLMMD-GEOIPS/recenter_tc/pulls?q=is%3Apr+is%3Aclosed
* Review "Files changed" tab
* Confirm appropriate testing was completed for these updates.

# Summary
Changes for version 1.9.1 update on repo recenter_tc.

Version 1.8.0 includes:
*************************

* Update to class-based plugin interfaces
* Update to setuptools_scm versioning (remove VERSION file)
* Update code to black defaults

Version 1.8.1 includes:
**************************

* SSMI/S 89GHz -> 91 GHz product name

Version 1.9.1 (2023-04-04)
**************************

* Remove GEOIPS BASEDIR references

See NRLMMD-GEOIPS/geoips#127 for additional repositories included in this update.

# Testing Instructions

Install GEOIPS and clone v1.9.1-release branch for:
* recenter_tc
* geoips

Tests should return 0:
$GEOIPS_PACKAGES_DIR/geoips/tests/test_full_install.sh

# Output
Pending

# Post Merge Steps
Once this PR has been merged, v1.9.1 will be tagged/released on the recenter_tc main branch.

### CODE REVIEW

**Comment by jsolbrig** [comment]
#### [Full log output](https://github.com/NRLMMD-GEOIPS/recenter_tc/files/11164015/test_all.log)

@mindy, I'm finally testing this. What I've found:
- The testing instructions didn't mention needing to install akima
- There is still one problematic environment variable, `$GEOIPS`. When it is set to `GEOIPS=$GEOIPS_PACKAGES_DIR/geoips` things work fine, but I don't normally have that set.
- I had a few failures due to missing test data. Datasets that I'm missing are:
  - test_data_ahi_day
  - test_data_amsub
  - test_data_modis
  - test_data_saphir
  - test_data_sar
  - test_data_smos
  - test_data_ssmis
  - test_data_ssmi
  - test_data_hy2
- I'm also running into an error in `gmi.tc.89pct.imagery_clean.sh` [test_all_recenter_tc.log_gmi.tc.89pct.imagery_clean.sh.log](https://github.com/NRLMMD-GEOIPS/recenter_tc/files/11164012/test_all_recenter_tc.log_gmi.tc.89pct.imagery_clean.sh.log)

**Comment by lance-wilson** [comment]
@mindyls 
For the recenter_tc test_all.sh, my experience was pretty much the same as @jsolbrig , except I had sar data so that passed.

For the $GEOIPS_PACKAGES_DIR/geoips/tests/test_full_install.sh tests, I ran into the following issues:
 * build_docs.sh: failed finding attribute '\_\_version\_\_' in 'geoips'
[test_all_geoips_full.log_build_docs.sh___home_lwilson_geoproc_geoips_packages_geoips_tests_..__html_only.log](https://github.com/NRLMMD-GEOIPS/recenter_tc/files/11289877/test_all_geoips_full.log_build_docs.sh___home_lwilson_geoproc_geoips_packages_geoips_tests_.__html_only.log)
 * test_interfaces:
   * algorithms fails due to not being able to find "modules.algorithms.stitched"
   * proclows fails due to not being able to find "geoips.plugins.modules.procflows.single_source" (appears this hasn't been moved yet)
[test_all_geoips_full.log_test_interfaces.log](https://github.com/NRLMMD-GEOIPS/recenter_tc/files/11289944/test_all_geoips_full.log_test_interfaces.log)
 * smap.unsectored.text_winds.sh: no text file in the compare path
[test_all_geoips_full.log_smap.unsectored.text_winds.sh.log](https://github.com/NRLMMD-GEOIPS/recenter_tc/files/11289883/test_all_geoips_full.log_smap.unsectored.text_winds.sh.log)
 * clavrx tests:  all successful except for flake8, which has several messages, usually stating a variable or function name should be lowercase
 * data_fusion:  fails at the argument stage; I'm guessing this is due to my in progress changes, though.

**Comment by mindyls** [comment]
I will open issues for @jsolbrig comments, and then are we ok to approve this one?

@lance-wilson  - I think once this gets merged to integration, then merged back into your plugins branch, it will make it easier to diagnose your other issues.

**Review by lance-wilson — COMMENTED** [review]
I'm good with this.

**Review by lance-wilson — APPROVED** [review]

**Review by jsolbrig — APPROVED** [review]
Looks good to me!

**Pull request merged**
